[font]
normal = { family = "Consolas NF" }


# Colors (Tomorrow Night Eighties)
[colors.primary]
background= "0x2d2d2d"  # base 05
foreground= "0xd3c0c8"  # base 00

[colors.cursor]
cursor= "0xd3d0c8"  # base 00
text=   "0xd3d0c8"  # base 05

[colors.normal]
black=   "0x2d2d2d"  # base 00
red=     "0xf2777a"  # base 08
green=   "0x99cc99"  # base 0B
yellow=  "0xffcc66"  # base 0A
blue=    "0x6699cc"  # base 0D
magenta= "0xcc99cc"  # base 0E
cyan=    "0x66cccc"  # base 0C
white=   "0xd3d0c8"  # base 05

[colors.bright]
black=   "0x747369"  # base 03
red=     "0xf2777a"  # base 08
green=   "0x99cc99"  # base 0B
yellow=  "0xffcc66"  # base 0A
blue=    "0x6699cc"  # base 0D
magenta= "0xcc99cc"  # base 0E
cyan=    "0x66cccc"  # base 0C
white=   "0xf2f0ec"  # base 07
