theme = "base16_transparent"

[editor]
end-of-line-diagnostics = "hint"
rulers = [
    80,  # Rust max comment len
    100, # Rust max line len
]

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.statusline]
left = [
    "mode",
    "file-name",
    "read-only-indicator",
    "file-modification-indicator"
]
right = [
    "diagnostics",
    "spinner",
    "file-name",
    "selections",
    "register",
    "position",
    "file-encoding",
]

[editor.indent-guides]
render = true
character = "╎"

[keys.normal]
# Print the current line's git blame information to the statusline.
space.B = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"
