# ensure things like `compdef` load correctly`
autoload -Uz compinit
compinit

# set locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_ALL=en_US.UTF-8

# set vim mode
set -o vi

# set path
export PATH=/opt/homebrew/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/yosh/.cargo/bin
export SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock
export PATH=/Users/$USER/bin:$PATH
export WASMTIME_HOME="$HOME/.wasmtime"
export PATH="$WASMTIME_HOME/bin:$PATH"
export PATH="/opt/homebrew/opt/llvm/bin:$PATH"

# wasm-tools completions
source "$HOME/.zsh/completions/wasm-tools"

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# atuin
. "$HOME/.atuin/bin/env"
eval "$(atuin init zsh)"

# setup aliases
alias ls="eza -lahG --icons=auto --no-permissions --no-user --icons=always --time-style='+%Y-%m-%d %H:%M' --sort type"
alias t="eza -lah --tree --icons=auto --no-permissions --no-user --icons=always --no-time --git-ignore --sort type"
alias cat="bat"
alias grep="rg"
eval "$(zoxide init zsh --cmd cd)"

# a few more quick shorthands
alias c="cargo"
alias k="kubectl"
alias g="git"


# init the prompt
eval "$(starship init zsh)"

# init zellij session
[[ -z "${ZELLIJ_SESSION_NAME}" ]] && [[ "$TERM_PROGRAM" != "vscode" ]] && zellij attach --create
